/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Castle(props) {
  const { nodes, materials } = useGLTF('/assets/3d/castle.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wonder_SecondAge_Level3_1.geometry}
          material={materials.Stone}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wonder_SecondAge_Level3_2.geometry}
          material={materials.Stone_Light}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wonder_SecondAge_Level3_3.geometry}
          material={materials.Wood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wonder_SecondAge_Level3_4.geometry}
          material={materials.Main}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/3d/castle.glb')