/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: berkay.tari (https://sketchfab.com/berkay.tari)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-mine-986760dffcbe4c069d20143f99dabe79
Title: Low Poly Mine
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Cave(props) {
  const { nodes, materials } = useGLTF('/assets/3d/low_poly_mine.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2410.471, 84.952, -1926.712]}
          scale={[1.464, 0.816, 1.542]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2272.34, 174.201, -1891.454]}
          rotation={[0, 0.223, -Math.PI]}
          scale={[-1.721, 0.443, 0.852]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.KapiSol_Material002_0.geometry}
          material={materials['Material.002']}
          position={[2163.216, 59.566, -88.118]}
          scale={[0.804, 0.961, 0.804]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.KapiSag_Material002_0.geometry}
          material={materials['Material.002']}
          position={[2644.46, 71.472, -114.689]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.76, 1.075, 0.76]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1868.983, 163.006, -571.881]}
          rotation={[0, 1.141, -Math.PI]}
          scale={[-2.459, 0.633, 1.217]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2012.08, 205.856, -1712.483]}
          rotation={[0, 0.441, -Math.PI]}
          scale={[-2.459, 0.823, 1.217]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1830.955, 111.382, -397.64]}
          rotation={[-Math.PI, 1.243, 0]}
          scale={[-1.726, 0.444, 0.854]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube011_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1975.265, 205.856, -300.069]}
          rotation={[-Math.PI, 0.79, 0]}
          scale={[-2.459, 0.823, 1.217]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2780.38, 110.522, -370.05]}
          rotation={[Math.PI, -0.74, 0]}
          scale={[-1.721, 0.443, 0.852]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2993.174, 163.006, -811.637]}
          rotation={[0, -1.483, Math.PI]}
          scale={[-2.459, 0.633, 1.217]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2973.692, 205.856, -556.559]}
          rotation={[Math.PI, -0.959, 0]}
          scale={[-2.459, 0.823, 1.217]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube016_Kaya_0.geometry}
          material={materials.Kaya}
          position={[3469.608, 52.593, -1149.913]}
          rotation={[0, -0.267, -Math.PI]}
          scale={[-1.726, 0.444, 0.854]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2632.521, 205.856, -1859.049]}
          rotation={[0, 0.186, -Math.PI]}
          scale={[-2.459, 0.823, 1.217]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube012_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2717.132, 134.985, -199.061]}
          scale={[1.064, 1.287, 1.121]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube018_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2069.333, 62.743, -73.469]}
          scale={[1.064, 1.287, 1.121]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1975.265, 314.706, -1800.949]}
          rotation={[-1.026, 1.488, 2.612]}
          scale={[-1.823, 0.611, 0.902]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube019_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2795.781, 314.706, -1905.755]}
          rotation={[-1.026, 1.488, 2.612]}
          scale={[-1.823, 0.611, 0.902]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_Kaya_0.geometry}
          material={materials.Kaya}
          position={[3017.828, 14.939, -2844.136]}
          rotation={[-1.527, 0.172, -3.135]}
          scale={[-1.157, 0.387, 0.573]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube021_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2660.502, 336.167, -1883.546]}
          rotation={[0, 0.223, -Math.PI]}
          scale={[-1.721, 0.443, 0.852]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube022_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2425.103, 51.042, -2071.343]}
          scale={[0.802, 0.447, 0.844]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube023_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2349.448, 128.028, -2137.402]}
          rotation={[0, 0.223, -Math.PI]}
          scale={[-0.943, 0.243, 0.467]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube024_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2128.53, 93.793, -1940.948]}
          rotation={[0, 1.141, -Math.PI]}
          scale={[-1.347, 0.347, 0.666]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube025_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2206.904, 117.262, -1954.01]}
          rotation={[0, 0.441, -Math.PI]}
          scale={[-1.347, 0.451, 0.666]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube026_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2851.324, 93.793, -2024.396]}
          rotation={[0, 0.025, -Math.PI]}
          scale={[-1.347, 0.347, 0.666]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube027_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2698.79, 65.518, -2051.27]}
          rotation={[0, -0.267, -Math.PI]}
          scale={[-0.945, 0.243, 0.468]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube028_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2546.719, 117.262, -2034.284]}
          rotation={[0, 0.186, -Math.PI]}
          scale={[-1.347, 0.451, 0.666]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube029_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2783.448, 338.199, -556.559]}
          rotation={[Math.PI, -1.327, 0]}
          scale={[-2.927, 0.98, 1.449]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube030_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2869.252, 378.678, -1642.008]}
          rotation={[-1.548, -1.414, 0.008]}
          scale={[-2.927, 0.98, 1.449]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube031_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2298.796, 274.192, -1806.723]}
          scale={[3.238, 1.333, 1.333]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.KapiUst_Material002_0.geometry}
          material={materials['Material.002']}
          position={[2163.216, 723.559, -88.118]}
          rotation={[0, 0.052, -1.441]}
          scale={[0.802, 0.828, 0.804]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube033_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2567.409, 928.82, -183.024]}
          rotation={[Math.PI, -0.063, 0]}
          scale={[-2.459, 0.823, 1.217]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube034_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2215.174, 871.111, -154.143]}
          rotation={[-1.519, -0.048, -3.034]}
          scale={[-1.588, 0.532, 0.786]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2807.583, 941.322, -450.272]}
          rotation={[1.408, -0.056, 1.817]}
          scale={[-2.459, 0.823, 1.217]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube036_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2033.11, 538.461, -199.794]}
          rotation={[0.157, -1.104, 2.022]}
          scale={[3.238, 1.333, 1.333]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube037_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1729.835, 82.251, -1676.865]}
          rotation={[1.669, -0.056, 1.956]}
          scale={[-4.571, 1.53, 2.262]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube038_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1986.357, 82.251, -1946.479]}
          rotation={[3.102, -0.056, 1.956]}
          scale={[-1.735, 0.581, 0.859]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube039_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2869.252, 601.038, -551.521]}
          rotation={[-2.52, -1.419, -1.927]}
          scale={[-2.927, 0.98, 1.449]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube040_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2704.955, 601.038, -257.967]}
          rotation={[-0.339, 1.243, -1.232]}
          scale={[-2.927, 0.98, 1.449]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube041_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2825.352, 424.045, -563.924]}
          rotation={[-2.729, 1.488, 2.612]}
          scale={[-1.591, 0.533, 0.787]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube042_Kaya_0.geometry}
          material={materials.Kaya}
          position={[3296.554, 123.392, -898.926]}
          rotation={[1.742, -0.034, 2.085]}
          scale={[-2.927, 0.98, 1.449]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube043_Kaya_0.geometry}
          material={materials.Kaya}
          position={[3178.074, 65.077, -1146.063]}
          rotation={[1.742, -0.034, 2.085]}
          scale={[-1.503, 0.503, 0.744]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube044_Kaya_0.geometry}
          material={materials.Kaya}
          position={[3016.594, 65.077, -1182.222]}
          rotation={[2.085, 1.168, 1.077]}
          scale={[-0.805, 0.27, 0.399]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube045_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2298.796, 1032.263, -408.093]}
          rotation={[1.509, 0, 0]}
          scale={[3.238, 1.333, 1.333]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube046_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2701.973, 1089.186, -618.825]}
          rotation={[1.964, -0.059, 1.844]}
          scale={[3.402, 1.313, 1.275]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube047_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2386.144, 1117.084, -726.947]}
          rotation={[1.818, -0.018, 1.065]}
          scale={[4.676, 1.333, 1.333]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube048_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2017.275, 1117.084, -726.947]}
          rotation={[1.848, -0.101, 1.749]}
          scale={[4.333, 1.66, 1.333]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube049_Tas_0.geometry}
          material={materials.material}
          position={[2108.595, 1155.476, -435.388]}
          rotation={[1.756, -0.101, 1.749]}
          scale={[0.599, 0.229, 0.184]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube050_Tas_0.geometry}
          material={materials.material}
          position={[2676.229, 1077.841, -404.007]}
          rotation={[1.756, -0.101, 1.749]}
          scale={[0.495, 0.388, 0.31]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube051_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2295.045, 1327.846, -914.817]}
          rotation={[-1.773, 0.422, -1.328]}
          scale={[1.225, 0.961, 0.768]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube052_Tas_0.geometry}
          material={materials.material}
          position={[2253.37, 1289.111, -881.146]}
          rotation={[1.641, -0.101, 1.749]}
          scale={[1.746, 0.669, 0.537]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2023.269, 591.475, -1456.487]}
          rotation={[3.139, -0.067, 1.334]}
          scale={[-4.571, 1.53, 2.262]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube054_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1829.036, 889.83, -714.241]}
          rotation={[2.571, -0.067, 1.334]}
          scale={[-2.862, 0.958, 1.416]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube055_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1927.646, 889.83, -543.513]}
          rotation={[-1.436, 0.037, 2.096]}
          scale={[-2.862, 0.958, 1.416]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube056_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2026.663, 862.572, -265.446]}
          rotation={[-0.185, -1.232, 2.916]}
          scale={[-2.065, 0.692, 1.022]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube057_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2821.104, 741.823, -1526.818]}
          rotation={[2.698, -1.03, -2.291]}
          scale={[-3.195, 0.893, 1.62]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube058_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1474.093, 361.049, -670.031]}
          rotation={[-2.984, -0.055, 2.064]}
          scale={[7.107, 0.89, 1.437]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube059_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1729.835, 374.114, -599.587]}
          rotation={[0.169, -0.212, 1.272]}
          scale={[-2.506, 0.839, 1.24]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube060_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2008.834, 383.027, -1815.069]}
          rotation={[-2.991, 0.479, 2.281]}
          scale={[-5.783, 1.936, 2.862]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1547.003, 915.144, -942.043]}
          rotation={[2.221, 1.229, -2.192]}
          scale={[3.238, 1.333, 1.333]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube062_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2017.275, 943.23, -2227.728]}
          rotation={[0.572, 0.387, 1.35]}
          scale={[4.333, 1.66, 1.333]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2194.336, 68.077, -2482.931]}
          rotation={[0.521, 0.11, -0.032]}
          scale={[5.684, 2.178, 1.749]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube064_Tas_0.geometry}
          material={materials.material}
          position={[2023.137, 595.032, -2380.036]}
          rotation={[0.077, -0.137, 2.985]}
          scale={[-1.337, 0.344, 0.662]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube065_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1808.341, 557.336, -2254.665]}
          rotation={[0, -1.561, Math.PI]}
          scale={[-1.677, 0.432, 0.83]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube066_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1760.267, 533.175, -2279.309]}
          rotation={[-1.059, 0.49, -2.673]}
          scale={[-1.677, 0.432, 0.83]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube067_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1901.04, 491.692, -2351.031]}
          rotation={[0.233, 0.14, 0]}
          scale={[-1.677, 0.432, 0.83]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube068_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1610.851, 1024.671, -1877.306]}
          rotation={[0.371, 0.686, -1.79]}
          scale={[-2.562, 0.858, 1.268]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube069_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1557.504, 767.349, -2008.513]}
          rotation={[-1.461, -0.153, -1.684]}
          scale={[-1.572, 0.526, 0.778]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube070_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1637.283, 637.697, -2180.323]}
          rotation={[2.119, 1.365, -0.665]}
          scale={[-1.572, 0.526, 0.778]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube071_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1637.283, 637.697, -1669.129]}
          rotation={[1.608, 0.001, -1.916]}
          scale={[-2.347, 0.727, 3.685]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube072_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2792.618, 556.184, -1884.47]}
          rotation={[0.299, -0.054, 1.828]}
          scale={[-3.195, 0.893, 1.62]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube073_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2692.531, 554.062, -1815.069]}
          rotation={[0.046, -0.5, 1.29]}
          scale={[5.835, 1.64, 1.509]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube074_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2218.105, 1039.298, -1963.342]}
          rotation={[0.123, -0.074, -1.883]}
          scale={[3.238, 1.333, 1.333]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube075_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2218.105, 642.136, -2266.337]}
          rotation={[0.213, -0.127, 2.886]}
          scale={[3.238, 1.333, 1.333]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube076_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2792.618, 246.524, -2173.124]}
          rotation={[0.299, -0.054, 1.828]}
          scale={[-3.195, 0.893, 1.62]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube077_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2458.935, 556.184, -2127.802]}
          rotation={[0.574, 0.009, -2.705]}
          scale={[-3.195, 0.893, 1.62]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube078_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2227.595, 554.062, -2122.338]}
          rotation={[0.04, -0.117, 1.273]}
          scale={[5.835, 1.64, 1.509]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube079_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2963.488, 502.499, -1964.926]}
          rotation={[-0.493, 1.234, -0.617]}
          scale={[7.107, 0.89, 1.437]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube080_Kaya_0.geometry}
          material={materials.Kaya}
          position={[3362.075, 42.151, -1103.211]}
          rotation={[1.394, -0.059, 1.844]}
          scale={[3.402, 1.313, 1.275]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube081_Kaya_0.geometry}
          material={materials.Kaya}
          position={[3169.139, 128.425, -2484.033]}
          rotation={[0.144, 0.269, 3.073]}
          scale={[-5.73, 0.94, 3.311]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube082_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1456.874, -31.5, -1040.265]}
          rotation={[1.669, -0.056, 1.956]}
          scale={[-2.981, 1.459, 2.254]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube083_Yer_0.geometry}
          material={materials.material_3}
          position={[1705.16, -31.5, -2372.609]}
          rotation={[1.596, 0.005, 1.901]}
          scale={[-3.732, 3.079, 0.911]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube084_Yer_0.geometry}
          material={materials.material_3}
          position={[1861.966, -31.5, -206.479]}
          rotation={[1.59, 0.017, 2.444]}
          scale={[-3.732, 3.079, 0.911]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube085_Yer_0.geometry}
          material={materials.material_3}
          position={[3517.056, -31.5, -1210.012]}
          rotation={[1.581, -0.024, 0.54]}
          scale={[-3.732, 3.079, 0.911]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube086_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1981.556, 68.077, -2654.091]}
          rotation={[0.753, 0.302, 0.531]}
          scale={[4.273, 1.637, 1.315]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube087_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2194.336, 68.221, -2607.22]}
          rotation={[-1.858, 0.084, 0.089]}
          scale={[-3.237, 1.24, 0.996]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube088_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2587.326, -17.054, -2697.074]}
          rotation={[-1.095, -1.32, -1.108]}
          scale={[-1.387, 0.464, 0.686]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube089_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2195.478, 1216.117, -2055.749]}
          rotation={[0.694, -0.101, 1.749]}
          scale={[1.11, 0.425, 0.342]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube090_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1336.196, 262.342, -951.006]}
          rotation={[2.305, 1.353, -0.609]}
          scale={[-2.371, 0.539, 0.909]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube091_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1923.103, 53.93, -92.188]}
          rotation={[-Math.PI, 1.243, 0]}
          scale={[-1.014, 0.261, 0.502]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube092_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1544.092, 21.17, -92.188]}
          rotation={[Math.PI, -0.199, 0]}
          scale={[-1.014, 0.261, 0.502]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube093_Tas_0.geometry}
          material={materials.material}
          position={[1544.092, 51.957, -370.73]}
          rotation={[-1.241, -0.122, -0.027]}
          scale={[-1.215, 0.313, 0.601]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube094_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1216.963, 3.437, -527.413]}
          rotation={[-1.423, -0.319, -0.813]}
          scale={[-1.014, 0.261, 0.502]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube095_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1660.58, -12.928, -187.566]}
          rotation={[-3.001, 0.142, 2.357]}
          scale={[-1.014, 0.261, 0.502]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube096_Tas_0.geometry}
          material={materials.material}
          position={[3083.613, 8.99, -493.865]}
          rotation={[-1.238, 0.113, 0.631]}
          scale={[-1.014, 0.261, 0.502]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube097_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2832.072, 8.99, -273.768]}
          rotation={[-1.238, 0.113, 0.631]}
          scale={[-1.014, 0.261, 0.502]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube098_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2994.912, 11.112, -397.097]}
          rotation={[-1.118, 0.623, 0.397]}
          scale={[-1.014, 0.261, 0.502]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube099_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2994.912, -25.19, -294.786]}
          rotation={[-3.119, -0.661, -3.105]}
          scale={[1.537, 0.141, 0.791]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube100_Tas_0.geometry}
          material={materials.material}
          position={[3373.973, 42.698, -763.434]}
          rotation={[2.83, 0.524, 1.793]}
          scale={[-0.745, 0.192, 0.369]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube101_Kaya_0.geometry}
          material={materials.Kaya}
          position={[3490.391, 42.698, -1008.949]}
          rotation={[1.432, 0.524, 1.793]}
          scale={[-1.014, 0.261, 0.502]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube102_Kaya_0.geometry}
          material={materials.Kaya}
          position={[3866.832, 25.531, -1193.087]}
          rotation={[1.432, 0.524, 1.793]}
          scale={[-1.014, 0.261, 0.502]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube103_Kaya_0.geometry}
          material={materials.Kaya}
          position={[3548.321, 42.698, -1298.282]}
          rotation={[0.878, 0.524, 1.793]}
          scale={[-1.014, 0.261, 0.502]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube104_Kaya_0.geometry}
          material={materials.Kaya}
          position={[3524.672, 5.932, -763.434]}
          rotation={[-2.205, 0.524, 1.793]}
          scale={[-1.014, 0.261, 0.502]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube105_Kaya_0.geometry}
          material={materials.Kaya}
          position={[3429.572, 29.106, -527.445]}
          rotation={[-2.618, 0.313, 0.14]}
          scale={[-1.014, 0.261, 0.502]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube106_Kaya_0.geometry}
          material={materials.Kaya}
          position={[3694.531, 25.531, -1439.793]}
          rotation={[1.694, 0.039, 1.375]}
          scale={[-1.014, 0.261, 0.502]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube107_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2681.791, -16.308, -2741.66]}
          rotation={[-1.699, 0.123, -2.077]}
          scale={[-1.157, 0.387, 0.573]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube108_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1678.096, -0.379, -2676.447]}
          rotation={[-0.196, -0.935, -0.105]}
          scale={[-1.387, 0.464, 0.686]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube109_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1737.001, 8.225, -2762.286]}
          rotation={[-1.743, -0.088, -1.58]}
          scale={[-1.157, 0.387, 0.573]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube110_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1924.307, 21.241, -2770.882]}
          rotation={[-0.353, -1.114, 0.777]}
          scale={[-1.387, 0.464, 0.686]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube111_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1993.476, 22.244, -2841.081]}
          rotation={[-2.759, -0.438, -1.917]}
          scale={[-1.157, 0.387, 0.573]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube112_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2094.014, -12.018, -2896.83]}
          rotation={[-0.937, -1.382, -1.173]}
          scale={[-1.387, 0.464, 0.686]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube113_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2190.004, 2.311, -2935.466]}
          rotation={[-1.473, 0.078, -2.122]}
          scale={[-1.157, 0.387, 0.573]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube114_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2353.456, -21.591, -2845.805]}
          rotation={[-1.825, -1.319, -1.026]}
          scale={[-1.387, 0.464, 0.686]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube115_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2449.3, -19.918, -2868.708]}
          rotation={[-2.51, 0.111, -2.06]}
          scale={[-1.157, 0.387, 0.573]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube116_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1503.493, -9.046, -2172.036]}
          rotation={[0.01, -0.935, -0.105]}
          scale={[-1.387, 0.464, 0.686]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube117_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1514.135, 42.402, -2254.313]}
          rotation={[-1.538, -0.088, -1.58]}
          scale={[-1.157, 0.387, 0.573]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube118_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1668.573, 20.077, -2294.503]}
          rotation={[0.006, 0.274, -0.114]}
          scale={[-1.387, 0.464, 0.686]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube119_Tas_0.geometry}
          material={materials.material}
          position={[1594.951, 46.015, -2357.449]}
          rotation={[-1.477, 0, -0.373]}
          scale={[-1.157, 0.387, 0.573]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube120_Tas_0.geometry}
          material={materials.material}
          position={[1143.831, -27.898, -1123.865]}
          rotation={[-0.162, -0.341, -0.035]}
          scale={[-1.387, 0.464, 0.686]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube121_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1103.128, 5.562, -1206.044]}
          rotation={[-1.688, -0.126, -0.982]}
          scale={[-1.157, 0.387, 0.573]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube122_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1210.14, -31.874, -1320.55]}
          rotation={[-0.269, 0.864, -0.009]}
          scale={[-1.387, 0.464, 0.686]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube123_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1112.306, -15.395, -1335.11]}
          rotation={[-1.687, -0.019, 0.223]}
          scale={[-1.157, 0.387, 0.573]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube124_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1099.162, 3.437, -832.956]}
          rotation={[-1.423, -0.319, -0.813]}
          scale={[-1.014, 0.261, 0.502]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube125_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1109.426, -85.449, -478.803]}
          rotation={[-0.115, -0.107, 0.003]}
          scale={[-1.387, 0.464, 0.686]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube126_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1050.593, -10.84, -547.808]}
          rotation={[-1.616, -0.15, -0.744]}
          scale={[-1.157, 0.387, 0.573]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube127_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1127.78, -42.992, -685.551]}
          rotation={[-0.343, 1.088, 0.126]}
          scale={[-1.387, 0.464, 0.686]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube128_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1029.258, -26.864, -676.141]}
          rotation={[-1.641, -0.046, 0.458]}
          scale={[-1.157, 0.387, 0.573]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube129_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2651.896, 47.089, -233.424]}
          rotation={[-Math.PI, 0.16, 0]}
          scale={[-1.726, 0.444, 0.854]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube130_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2151.189, 19.94, -233.424]}
          rotation={[-2.734, -0.869, 0.46]}
          scale={[-1.726, 0.444, 0.854]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube131_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2017.275, 1117.084, -1351.785]}
          rotation={[1.309, -0.101, 1.749]}
          scale={[7.004, 1.717, 1.41]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube132_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2262.515, 1197.651, -1340.315]}
          rotation={[1.253, 0.126, 1.744]}
          scale={[7.004, 1.717, 1.41]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube133_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2839.756, 1197.651, -1659.79]}
          rotation={[1.253, 0.126, 1.744]}
          scale={[3.636, 2.2, 1.363]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube134_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2839.756, 1197.651, -1125.145]}
          rotation={[-1.472, 0.126, 1.744]}
          scale={[3.65, 2.541, 1.366]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube135_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2295.045, 1327.846, -1417.414]}
          rotation={[-1.834, 0.791, -1.222]}
          scale={[1.225, 0.961, 0.768]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube136_Tas_0.geometry}
          material={materials.material}
          position={[2344.502, 1310.317, -1402.593]}
          rotation={[0.656, 1.274, 1.074]}
          scale={[1.225, 0.961, 0.768]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube137_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2439.035, 1327.846, -1417.414]}
          rotation={[-1.76, 0.238, -1.367]}
          scale={[1.225, 0.961, 0.768]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube138_Kaya_0.geometry}
          material={materials.Kaya}
          position={[3134.226, 205.856, -1019.833]}
          rotation={[Math.PI, -1.242, 0]}
          scale={[-2.459, 0.823, 1.217]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube139_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2951.578, 338.199, -966.614]}
          rotation={[0, -1.531, Math.PI]}
          scale={[-2.927, 0.98, 1.449]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube140_Kaya_0.geometry}
          material={materials.Kaya}
          position={[3035.365, 601.038, -985.781]}
          rotation={[-0.505, -1.388, 0.101]}
          scale={[-2.927, 0.98, 1.449]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube141_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2959.746, 601.038, -657.985]}
          rotation={[-1.33, 1.46, -0.227]}
          scale={[-2.927, 0.98, 1.449]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube142_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2989.748, 424.045, -985.407]}
          rotation={[-3.047, 1.21, 2.936]}
          scale={[-1.591, 0.533, 0.787]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube143_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2911.382, 375.607, -1260.066]}
          rotation={[-2.932, -0.462, -1.445]}
          scale={[-2.927, 0.98, 1.449]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube144_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2884.973, 744.893, -1247.772]}
          rotation={[2.925, 0.009, -1.847]}
          scale={[-3.195, 0.893, 1.62]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube145_Kaya_0.geometry}
          material={materials.Kaya}
          position={[3115.69, 424.045, -1135.255]}
          rotation={[-1.058, 1.226, 0.96]}
          scale={[-1.591, 0.533, 0.787]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube146_Kaya_0.geometry}
          material={materials.Kaya}
          position={[3115.69, 279.847, -1135.255]}
          rotation={[-2.516, 1.226, 0.96]}
          scale={[-1.591, 0.533, 0.787]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube147_Tas_0.geometry}
          material={materials.material}
          position={[3127.991, 179.77, -1234.099]}
          rotation={[2.539, 1.232, 2.245]}
          scale={[-0.987, 0.33, 0.488]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube148_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2957.201, 81.964, -1686.991]}
          rotation={[1.295, 0.137, -1.512]}
          scale={[-2.927, 0.98, 1.449]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube149_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2992.408, 31.462, -1466.004]}
          rotation={[1.618, 0.005, -1.759]}
          scale={[3.402, 1.313, 1.275]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube150_Kaya_0.geometry}
          material={materials.Kaya}
          position={[3153.846, 174.505, -1663.848]}
          rotation={[-3.058, 1.432, -0.223]}
          scale={[-2.459, 0.823, 1.217]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube151_Kaya_0.geometry}
          material={materials.Kaya}
          position={[3154.889, 21.794, -1987.182]}
          rotation={[1.723, 0.004, 2.44]}
          scale={[3.402, 1.313, 1.275]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube152_Yer_0.geometry}
          material={materials.material_3}
          position={[3234.382, -31.5, -1618.755]}
          rotation={[1.578, 0.025, 2.99]}
          scale={[-3.732, 3.079, 0.911]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube153_Kaya_0.geometry}
          material={materials.Kaya}
          position={[3304.289, 52.593, -1916.64]}
          rotation={[0, -0.267, -Math.PI]}
          scale={[-1.726, 0.444, 0.854]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube154_Kaya_0.geometry}
          material={materials.Kaya}
          position={[3295.262, 42.698, -1775.676]}
          rotation={[1.432, 0.524, 1.793]}
          scale={[-1.014, 0.261, 0.502]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube155_Tas_0.geometry}
          material={materials.material}
          position={[3383.002, 42.698, -2065.009]}
          rotation={[0.878, 0.524, 1.793]}
          scale={[-1.014, 0.261, 0.502]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube156_Kaya_0.geometry}
          material={materials.Kaya}
          position={[3476.272, -21.896, -1653.428]}
          rotation={[-1.721, -0.614, -1.849]}
          scale={[-1.014, 0.261, 0.502]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube157_Kaya_0.geometry}
          material={materials.Kaya}
          position={[3537.473, 25.531, -2237.179]}
          rotation={[1.432, 0.524, 1.793]}
          scale={[-1.014, 0.261, 0.502]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube158_Kaya_0.geometry}
          material={materials.Kaya}
          position={[3472.292, -26.251, -1916.64]}
          rotation={[0.091, -0.251, -2.791]}
          scale={[-1.726, 0.444, 0.854]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube159_Kaya_0.geometry}
          material={materials.Kaya}
          position={[3549.815, -9.406, -2065.009]}
          rotation={[0.696, 0.766, 2.092]}
          scale={[-1.014, 0.261, 0.502]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube160_Kaya_0.geometry}
          material={materials.Kaya}
          position={[3035.365, 889.132, -985.781]}
          rotation={[1.365, -1.227, 1.617]}
          scale={[-3.556, 0.99, 0.929]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube161_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2992.887, 827.219, -682.131]}
          rotation={[2.36, -0.949, 2.465]}
          scale={[-2.612, 0.727, 0.682]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube162_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2885.608, 1034.846, -682.131]}
          rotation={[2.594, -0.989, 1.099]}
          scale={[-1.999, 1.223, 0.827]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube163_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2728.571, 404.339, -1429.627]}
          rotation={[-2.888, 0.527, -1.725]}
          scale={[-4.938, 1.381, 2.505]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube164_Kaya_0.geometry}
          material={materials.Kaya}
          position={[2640.847, 744.113, -1429.627]}
          rotation={[2.408, 1.239, -0.779]}
          scale={[-4.938, 1.381, 2.505]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube165_Yer_0.geometry}
          material={materials.material_3}
          position={[1523.212, -21.474, -1689.231]}
          rotation={[1.6, 0.068, 1.952]}
          scale={[-5.153, 2.498, 0.787]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube166_Tas_0.geometry}
          material={materials.material}
          position={[1299.631, 43.357, -1674.563]}
          rotation={[-1.665, -0.338, -1.532]}
          scale={[-0.731, 0.188, 0.362]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube167_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1185.424, -45.529, -1704.293]}
          rotation={[-0.161, -0.781, -0.098]}
          scale={[-1.387, 0.464, 0.686]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube168_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1182.995, 29.08, -1794.942]}
          rotation={[-1.7, -0.088, -1.425]}
          scale={[-1.157, 0.387, 0.573]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube169_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1329.579, -3.072, -1853.628]}
          rotation={[-0.172, 0.428, -0.109]}
          scale={[-1.387, 0.464, 0.686]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube170_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1247.011, 13.056, -1908.195]}
          rotation={[-1.654, 0.008, -0.219]}
          scale={[-1.157, 0.387, 0.573]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube171_Kaya_0.geometry}
          material={materials.Kaya}
          position={[914.622, -83.189, -1704.293]}
          rotation={[-0.161, -0.781, -0.098]}
          scale={[-1.387, 0.464, 0.686]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube172_Kaya_0.geometry}
          material={materials.Kaya}
          position={[912.192, -8.58, -1794.942]}
          rotation={[-1.7, -0.088, -1.425]}
          scale={[-1.157, 0.387, 0.573]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube173_Kaya_0.geometry}
          material={materials.Kaya}
          position={[976.209, -24.604, -1908.195]}
          rotation={[-1.654, 0.008, -0.219]}
          scale={[-1.157, 0.387, 0.573]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube174_Kaya_0.geometry}
          material={materials.Kaya}
          position={[914.622, -99.069, -2419.226]}
          rotation={[-0.161, -0.781, -0.098]}
          scale={[-1.387, 0.464, 0.686]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube175_Kaya_0.geometry}
          material={materials.Kaya}
          position={[912.192, -24.46, -2509.875]}
          rotation={[-1.7, -0.088, -1.425]}
          scale={[-1.157, 0.387, 0.573]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube176_Kaya_0.geometry}
          material={materials.Kaya}
          position={[976.209, -40.484, -2623.128]}
          rotation={[-1.654, 0.008, -0.219]}
          scale={[-1.157, 0.387, 0.573]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube177_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1117.369, -99.069, -2196.903]}
          rotation={[-0.121, 0.335, 0.056]}
          scale={[-1.387, 0.464, 0.686]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube178_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1034.557, -24.46, -2233.853]}
          rotation={[-1.547, -0.154, -0.294]}
          scale={[-1.157, 0.387, 0.573]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube179_Kaya_0.geometry}
          material={materials.Kaya}
          position={[960.046, -40.484, -2340.495]}
          rotation={[-1.614, -0.072, 0.903]}
          scale={[-1.157, 0.387, 0.573]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube180_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1106.833, -82.742, -2826.522]}
          rotation={[3.108, -1.396, 2.996]}
          scale={[-1.387, 0.464, 0.686]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube181_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1173.801, -31.294, -2875.492]}
          rotation={[-1.612, -0.084, -2.394]}
          scale={[-1.157, 0.387, 0.573]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube182_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1309.329, -53.619, -2791.24]}
          rotation={[0.007, -0.537, -0.109]}
          scale={[-1.387, 0.464, 0.686]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube183_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1304.234, -27.681, -2887.969]}
          rotation={[-1.506, -0.068, -1.182]}
          scale={[-1.157, 0.387, 0.573]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube184_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1434.372, -27.681, -2813.902]}
          rotation={[-1.48, -0.021, -0.599]}
          scale={[-1.157, 0.387, 0.573]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube185_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1286.181, -33.939, -2419.226]}
          rotation={[-0.161, -0.781, -0.098]}
          scale={[-1.387, 0.464, 0.686]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube186_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1283.751, 40.67, -2509.875]}
          rotation={[-1.7, -0.088, -1.425]}
          scale={[-1.157, 0.387, 0.573]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube187_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1230.094, 17.517, -2334.781]}
          rotation={[-1.547, -0.154, -0.294]}
          scale={[-1.157, 0.387, 0.573]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube188_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1350.823, 28.1, -2509.875]}
          rotation={[-1.634, -0.064, 3.104]}
          scale={[-1.157, 0.387, 0.573]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube189_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1592.56, 911.082, -1182.887]}
          rotation={[-0.063, -0.083, -1.718]}
          scale={[-2.499, 1.519, 2.259]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube190_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1483.088, 191.928, -1081.368]}
          rotation={[0.583, 1.163, 0.45]}
          scale={[3.238, 1.333, 1.333]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube191_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1994.308, 269.703, -459.827]}
          rotation={[0.032, -0.512, 1.921]}
          scale={[3.238, 1.333, 1.333]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube192_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1548.01, 73.531, -599.587]}
          rotation={[-0.124, -0.241, 0.109]}
          scale={[-2.506, 0.839, 1.24]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube193_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1548.01, 187.117, -607.087]}
          rotation={[0.118, -0.742, -1.076]}
          scale={[-2.506, 0.839, 1.24]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube194_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1892.771, 661.533, -440.301]}
          rotation={[0.254, -0.653, 2.023]}
          scale={[-2.862, 0.958, 1.416]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube195_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1585.815, 614.222, -982.537]}
          rotation={[0.598, 1.176, 1.124]}
          scale={[3.238, 1.333, 1.333]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube196_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1547.003, 254.478, -1428.244]}
          rotation={[0.583, 1.163, 0.45]}
          scale={[3.238, 1.333, 1.333]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube197_Kaya_0.geometry}
          material={materials.Kaya}
          position={[1678.391, 600.401, -1324.938]}
          rotation={[-2.317, -1.485, 2.252]}
          scale={[-2.499, 1.519, 2.259]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_Tas_0.geometry}
          material={materials.material}
          position={[1912.807, 734.349, -195.728]}
          rotation={[-0.658, 1.015, -0.646]}
          scale={[-0.689, 0.177, 0.341]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006_Tas_0.geometry}
          material={materials.material}
          position={[1818.435, 1177.194, -1813.513]}
          rotation={[-0.74, 0.698, -0.796]}
          scale={[-0.828, 0.213, 0.41]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007_Tas_0.geometry}
          material={materials.material}
          position={[3015.406, 793.015, -628.214]}
          rotation={[2.539, 1.232, 2.245]}
          scale={[-0.835, 0.28, 0.413]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube032_Tas_0.geometry}
          material={materials.material}
          position={[2867.689, 489.079, -392.776]}
          rotation={[2.176, 0.1, 0.97]}
          scale={[-0.915, 0.235, 0.453]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube198_Tas_0.geometry}
          material={materials.material}
          position={[1593.655, 685.732, -1474.949]}
          rotation={[-1.665, -0.338, -1.532]}
          scale={[-1.014, 0.261, 0.502]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube199_Tas_0.geometry}
          material={materials.material}
          position={[2716.869, 675.184, -1970.247]}
          rotation={[0.077, -0.137, 2.985]}
          scale={[-1.347, 0.347, 0.666]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_Material001_0.geometry}
          material={materials['Material.001']}
          position={[2270.303, 0, -1475.099]}
          scale={18.061}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/3d/low_poly_mine.glb')

