/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Soldier1(props) {
  const { nodes, materials } = useGLTF('/assets/3d/soldier1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Body_Cylinder.geometry}
        material={materials.Skin}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Helmet_Cylinder002.geometry}
        material={materials.Bronze}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Boots_Cylinder004.geometry}
        material={materials.Boots}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wrist_Guard_Cylinder005.geometry}
        material={materials.Bronze}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Shoulder_Cylinder006.geometry}
        material={materials.Bronze}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cloak_Cylinder001.geometry}
        material={materials.Red}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Shirt_Cylinder003-Mesh'].geometry}
        material={materials.Bronze}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Shirt_Cylinder003-Mesh_1'].geometry}
        material={materials['Boots.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Helm_top_Cube001-Mesh'].geometry}
        material={materials.Bronze}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Helm_top_Cube001-Mesh_1'].geometry}
        material={materials.Red}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Helm_top_Cube001-Mesh_2'].geometry}
        material={materials['Red.001']}
      />
    </group>
  )
}

useGLTF.preload('/assets/3d/soldier1.glb')