/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Tree1({ customColor = '#2d5a27', ...props }) {
  const { nodes, materials } = useGLTF('/assets/3d/tree1.glb')
  
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ель.geometry}
        // Ana ağaç yaprak rengi
        material={materials.Материал}
        material-color={customColor} 
        position={[2.668, 1.273, -1.174]}
        rotation={[1.592, -0.055, 0.492]}
        scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cone_1.geometry}
          material={materials.Материал}
          material-color={customColor}
          position={[-6.531, -1.187, -80.282]}
          rotation={[-0.023, 0.097, -0.585]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cone_2.geometry}
          material={materials.Материал}
          material-color={customColor}
          position={[-2.557, -1.11, -153.47]}
          rotation={[0.04, -0.009, -0.614]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder.geometry}
          material={materials['Материал.1']}
          position={[8.462, -10.072, 115.453]}
          rotation={[0.062, -0.036, -0.49]}
        />
      </mesh>
      
      {/* Çimen/Ot kısımları için renk uygulaması */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.трава_1.geometry}
        material={materials['Материал.002']}
        material-color={customColor}
        position={[-1.239, 0.452, 0.22]}
        rotation={[1.618, 0.099, 0.274]}
        scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pyramid_1.geometry}
          material={materials['Материал.002']}
          material-color={customColor}
          position={[-67.106, -18.952, 0]}
          rotation={[0, 0, -2.667]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pyramid_2.geometry}
          material={materials['Материал.002']}
          material-color={customColor}
          position={[-46.254, 56.769, 1.796]}
          rotation={[0.24, 0.104, -1.138]}
        />
      </mesh>

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.трава.geometry}
        material={materials['Материал.002']}
        material-color={customColor}
        position={[1.389, 0.383, -1.009]}
        rotation={[1.512, -0.142, 0.106]}
        scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pyramid_1_2.geometry}
          material={materials['Материал.002']}
          material-color={customColor}
          position={[-67.105, -18.952, 0]}
          rotation={[0, 0, -2.667]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pyramid_2_2.geometry}
          material={materials['Материал.002']}
          material-color={customColor}
          position={[-46.254, 56.769, 1.796]}
          rotation={[0.24, 0.104, -1.138]}
        />
      </mesh>

      {/* Yuvarlak yapraklı ağaç kısımları (Sphere) */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.древо.geometry}
        material={materials['Материал.003']}
        position={[0, 0.789, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere_2_3.geometry}
          material={materials['Материал.004']}
          material-color={customColor}
          position={[-140.351, 32.676, -504.843]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere_1_2.geometry}
          material={materials['Материал.004']}
          material-color={customColor}
          position={[196.967, 3.338, -582.786]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere_2_2.geometry}
          material={materials['Материал.004']}
          material-color={customColor}
          position={[157.399, 180.22, -297.611]}
          rotation={[0, 0, 0.524]}
        />
      </mesh>

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere_4.geometry}
        material={materials['Материал.2']}
        position={[-0.578, 0, -0.972]}
        rotation={[Math.PI / 2, 0, -2.048]}
        scale={0.01}
      />
    </group>
  )
}

useGLTF.preload('/assets/3d/tree1.glb')